name: Run Tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Generate coverage report
      run: |
        pip install pytest-cov
        pytest --cov-config=.coveragerc --cov=nerdpool_client/ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        #TODO COOKIETEMPLE: If your repository is private you are required to set a CODECOV_TOKEN as a secret into your Github repository.
        #See: https://docs.codecov.io/docs/about-the-codecov-bash-uploader#upload-token and
        #https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets.
        #No token is required if your repository is public.
        # token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false